
services:
###> doctrine/doctrine-bundle ###
  database:
    image: mariadb:10.5
    environment:
      MYSQL_DATABASE: ${MARIADB_DB:-app}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD:-!ChangeMe!}
      MYSQL_USER: ${MARIADB_USER:-app}
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-!ChangeMe!}
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/mysql:rw
      - ./docker/mariadb/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
